--DDL - Criando tabelas
DROP TABLE IF EXISTS work;
CREATE TABLE IF NOT EXISTS work_info(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT DEFAULT NULL,
    company TEXT DEFAULT NULL
);
DROP TABLE IF EXISTS contato;
CREATE TABLE IF NOT EXISTS contato(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT DEFAULT NULL,
    adress TEXT DEFAULT NULL,
    pic TEXT DEFAULT NULL,
    id_cont_social default null,
    id_contact_group DEFAULT NULL,
    id_work INTEGER DEFAULT NULL
);
DROP TABLE IF EXISTS grupo;
CREATE TABLE IF NOT EXISTS grupo(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT DEFAULT NULL,
    descrisption TEXT DEFAULT NULL
);
DROP TABLE IF EXISTS contact_group;
CREATE TABLE IF NOT EXISTS contact_group(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    id_contact INTEGER DEFAULT NULL,
    id_group INTEGER DEFAULT NULL
);
DROP TABLE IF EXISTS social_midia;
CREATE TABLE IF NOT EXISTS social_midia(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT DEFAULT NULL,
    user TEXT DEFAULT NULL,
    link TEXT DEFAULT NULL
);
DROP TABLE IF EXISTS contact_social;
CREATE TABLE IF NOT EXISTS contact_social(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    id_contac INTEGER DEFAULT NULL,
    id_soc_midia INTEGER DEFAULT NULL
);